In [4]:
import pandas as pd
from mod06_deanonymize import load_data, link_records, deanonymization_rate

In [5]:
anon_path = "mod06_data/anonymized.csv"
aux_path = "mod06_data/auxiliary.csv"

### Load and review the data

In [6]:
anon, aux = load_data(anon_path, aux_path)

In [7]:
anon.head(20)

   anon_id  age  zip3 gender
0    ERM5C   50   432      F
1    OFJJP   75   323      F
2    I3H24   44   323      M
3    3WUYW   66   323      M
4    ZN91P   18   323      M
5    7BLKV   36   606      F
6    4SJFH   70   890      M
7    0NO3L   31   110      M
8    U060Z   80   191      F
9    1761H   58   606      M
10   I9UI2   53   432      M
11   OO0ZT   47   941      F
12   BPEI7   19   112      M
13   ULMOZ   47   110      M
14   ES0E7   75   323      F
15   XCR1D   73   606      M
16   AY6JA   69   323      M
17   Q1J6V   40   941      F
18   BU6DU   54    62      F
19   LL1K7   69    21      M

### Merge the datasets by age, gender, and zip3 and return the unique matches

In [8]:
matches = link_records(anon, aux)
matches.head()

  anon_id   matched_name
0   ERM5C    Grace Lopez
1   ZN91P  Kyle Martinez
2   0NO3L   Marcus Lopez
3   U060Z    Sally Davis
4   1761H  Frank Jackson

### Calculate the match rate

In [9]:
rate = deanonymization_rate(matches, anon)
print(rate)

0.421

# Discussion Questions

### Describe your reaction to the match rate. What sources of data might be prone to privacy issues?

Honestly it was a little too easy to make all the people match up. It didn't seem very secure despite all the efforts to make things annonymized. There are privacy issues around how things are chategorized in general, we have access to everyones ages and their gender which are pretty specific. Even things like just part of a zip code is really helpful because all that combined means that algorithms can pinpoint things very quickly. For example, if the part of zip code is put in, we have general places people could live, which decreases the amount of data needed to shift through quite quickly. Then they can use age and gender of each area to guess at where people are in that area. Then the ability to cross compare with places with matching data sets makes it very easy to find the people themselves.

### Provide examples of at least two other variables that could increase the match rate if included.

Potential family members almost makes things easier, because then last name can be factored in to the equation. This is more around potential results because it is true people can have different last names even if they are in the same area. Another one could be their race like from homework 4. With race, the location of where people of similar races pair up can be taken into consideration. For example, if a person is of a specified race, we can then guess their location based off parts of the zip code plus where a majority of where people of that race live.